<?php


namespace App\Libraries;


use CodeIgniter\Database\BaseBuilder;
use CodeIgniter\Model;
use Config\Database;

class MyModel extends Model
{

//    public function __construct()
//    {
//        $connection = Database::connect();
//        parent::__construct($this->table, $connection );
//    }


//
//    public function select($select = '*', bool $escape = null)
//    {
//         return $this->builder()->select($select, $escape); // TODO: Change the autogenerated stub
//
//    }
//
//    public function get(int $limit = null, int $offset = 0, bool $reset = true)
//    {
//        return $this->builder()->get($limit, $offset, $reset); // TODO: Change the autogenerated stub
//    }
//
//    public function join(string $table, string $cond, string $type = '', bool $escape = null)
//    {
//        return $this->builder()->join($table, $cond, $type, $escape); // TODO: Change the autogenerated stub
//    }


}